backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
media_folder: static/img
public_folder: /img
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "/{{year}}-{{month}}-{{day}}/{{slug}}"
    editor:
      preview: true
    fields:
      - { label: 제목, name: title, widget: string }
      - { label: 날짜, name: date, widget: datetime }
      - { label: Slug, name: slug, widget: string }
      - { label: 기본 이미지, name: image, widget: string }
      - { label: 태그, name: tags, widget: list }
      - { label: 내용, name: body, widget: markdown }
